"""User-writable Python environment overlay.

The .app's bundled site-packages are read-only and code-signed. To let
users (and the agent's shell tool) `pip install` new packages, we set up
a writable overlay at ~/Library/Application Support/<AppName>/python-userbase
and configure the bundled Python to look there via PYTHONUSERBASE.

This module is idempotent: it can be called every launch and only does work
on first run.
"""

from __future__ import annotations

import os
import shutil
import stat
from pathlib import Path

from .paths import AppPaths


def _write_pip_conf(p: AppPaths) -> None:
    if p.pip_conf.exists():
        return
    p.pip_conf.parent.mkdir(parents=True, exist_ok=True)
    p.pip_conf.write_text(
        "# Generated by OpenKimo on first launch.\n"
        "# Forces `pip install` to drop packages into the user overlay\n"
        "# instead of the read-only signed bundle.\n"
        "[install]\n"
        "user = true\n"
        "\n"
        "[global]\n"
        "disable-pip-version-check = true\n"
    )


def _write_wrapper(target: Path, script: str) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(script)
    target.chmod(target.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def _ensure_wrappers(p: AppPaths) -> None:
    """Drop `python` / `pip` shims into userbase/bin so PATH-based lookup
    routes through the bundled interpreter and user overlay.
    """
    python_shim = p.userbase_bin / "python"
    pip_shim = p.userbase_bin / "pip"

    common = (
        f'export PYTHONUSERBASE="{p.userbase}"\n'
        f'export PIP_CONFIG_FILE="{p.pip_conf}"\n'
    )

    _write_wrapper(
        python_shim,
        '#!/bin/sh\n'
        + common
        + f'exec "{p.bundled_python}" "$@"\n',
    )
    # python3 alias
    python3_shim = p.userbase_bin / "python3"
    if python3_shim.is_symlink() or python3_shim.exists():
        try:
            python3_shim.unlink()
        except OSError:
            pass
    try:
        python3_shim.symlink_to(python_shim)
    except OSError:
        # File system without symlinks: fall back to a duplicate script.
        shutil.copy2(python_shim, python3_shim)

    _write_wrapper(
        pip_shim,
        '#!/bin/sh\n'
        + common
        + f'exec "{p.bundled_python}" -m pip "$@"\n',
    )
    pip3_shim = p.userbase_bin / "pip3"
    if pip3_shim.is_symlink() or pip3_shim.exists():
        try:
            pip3_shim.unlink()
        except OSError:
            pass
    try:
        pip3_shim.symlink_to(pip_shim)
    except OSError:
        shutil.copy2(pip_shim, pip3_shim)


def _maybe_install_cli_symlink(p: AppPaths) -> None:
    """If ~/.local/bin exists, expose the bundled CLI wrapper as `<slug>`."""
    target = p.cli_symlink
    src = p.cli_wrapper
    if not target.parent.exists() or not src.exists():
        return
    try:
        if target.is_symlink() or target.exists():
            if target.is_symlink() and target.resolve() == src.resolve():
                return
            target.unlink()
        target.symlink_to(src)
    except OSError:
        pass


def setup(p: AppPaths) -> None:
    """One-shot bootstrap: pip.conf + bin/ wrappers + ~/.local/bin symlink."""
    p.userbase.mkdir(parents=True, exist_ok=True)
    p.userbase_bin.mkdir(parents=True, exist_ok=True)
    _write_pip_conf(p)
    _ensure_wrappers(p)
    _maybe_install_cli_symlink(p)


def env_overlay(p: AppPaths) -> dict[str, str]:
    """Environment additions for any subprocess that should use the overlay.

    Used by `server.py` when spawning uvicorn and by the Install Package…
    pip subprocess.
    """
    sep = os.pathsep
    base_path = os.environ.get("PATH", "")
    return {
        "PYTHONUSERBASE": str(p.userbase),
        "PIP_CONFIG_FILE": str(p.pip_conf),
        "PATH": f"{p.userbase_bin}{sep}{p.bundled_python_bin}{sep}{base_path}",
    }


def reset(p: AppPaths) -> None:
    """Wipe the user overlay site-packages (kept for the future Reset menu)."""
    site_packages_root = p.userbase / "lib"
    if site_packages_root.exists():
        shutil.rmtree(site_packages_root, ignore_errors=True)
    site_packages_root.mkdir(parents=True, exist_ok=True)
