name: Sync to Gitee
on:
 push:
   branches: [ main ]
jobs:
 sync:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
       with:
         fetch-depth: 0
     - uses: wearerequired/git-mirror-action@v1
       env:
         SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
       with:
         source-repo: git@github.com:goldenxingxing/OpenKimo.git
         destination-repo: git@gitee.com:qunwei/OpenKimo.git
